"""应用名称与包名常量表，供 Agent 查询。"""


APP_NAME_PACKAGE_MAP = {
    "爱奇艺PAD": "com.qiyi.video.pad",
    "安全中心": "com.zui.safecenter",
    "便签": "com.zui.notes",
    "Canva可画": "cn.canva.editor",
    "超级互联": "com.motorola.mobiledesktop",
    "超级文件": "com.zui.filemanager",
    "服务与反馈": "com.tblenovo.center",
    "盖世游戏": "com.xiaoji.egggame",
    "画世界Pro": "net.huanci.hsjpro",
    "计算器": "com.zui.calculator",
    "快手": "com.smile.gifmaker",
    "Legion Zone": "com.lenovo.legionzone",
    "联想": "com.lenovo.club.app",
    "联想换机": "com.zui.clone",
    "联想云电脑": "com.lenovo.hybridworkspace",
    "浏览器": "com.zui.browser",
    "录音机": "com.zui.recorder",
    "Notein一笔记": "com.orion.notein",
    "日历": "com.zui.calendar",
    "设置": "com.android.settings",
    "时钟": "com.zui.deskclock",
    "天骄学堂HD": "com.lenovo.nceetj.educenterhd",
    "天气": "com.zui.weather",
    "天禧智能体": "com.lenovo.menu_assistant.hd",
    "通讯录": "com.zui.contacts",
    "图库": "com.zui.gallery",
    "网易云音乐": "com.netease.cloudmusic",
    "微博": "com.sina.weibo",
    "想帮帮": "com.lenovo.xbb",
    "相机": "com.zui.camera",
    "享做笔记": "com.newskyer.draw",
    "应用宝": "com.tencent.android.qqdownloader",
    "优酷视频": "com.youku.phone",
    "智慧文档": "com.lenovo.office",
    "360AI办公": "com.qihoo.aiwork",
}
